### ISSUE TITLE
rg-card difficulties

### ISSUE THREAD

**Issue by jahbini** [riotgear2/riotgear2.github.io#1]
i am attempting to use the following code from the rg-card page.
`var tags = riot.mount ("rg-card", {card: {
                            text: "My **precious** text, it's _mine_! It's _mine_!<br />",
                            header: {image: "https://unsplash.it/1024/500?random",
                                    text: "**Master** of the _Universe_",
                                    subhead: "Job Vacancy",
                                    divider: true,
//                                    style: "brand"
                                    },
                            footer: {
                                    text: "Do you like this?",
//                                    divider: true,
//                                    style: "warning",
//                                    block: true,
                                    items: [
                                      {text: "Yes"},
                                      {text: "Maybe", style: "warning"},
                                      {text: "No", style: "error"}
                                    ]}
    }}) ;

    tags[0].on("button-clicked", function (e) {console.log("button-clicked:", e)}) ;`

however, the mount 'often' fails to return the `tags` array, due to riot's async compilation step.

the work-around suggested at riot.js of wrapping the `mount` call inside a `riot.compile` does not seem to work to avoid this issue, if there are more than one `rg-card` on the page.

i am unable to find the actual source code of rg-card to zero in on how to cope with this behavior..

the actual card displays properly on the page, but i am unable to find out how to hook into the riot-tag `observable` before, during, or after the actual DOM element gets updated.

Any clues?

**Comment by adavie1** [comment]
Thanks for the feedback. I've already replied to your issue with the link to the full source code.
