### ISSUE TITLE
 Error on Website in Chrome Console 

### ISSUE THREAD

**Issue by jhoelzel** [riotgear2/riotgear2.github.io#2]
Hey Guys, 

I was just casually browsing and found this in my chrome console:

`Refused to apply style from 'https://unpkg.com/blaze@5.0.0/index.js' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
`

Furtermore it does not seem like i can see any styles of the new elements because of this. 
My Current firefox does not throw an error, but it does not seem like styles are applied either!

unpkg also returns 

`Cannot find "/index.js" in blaze@5.0.0`

https://unpkg.com/blaze@5.0.0/index.js

Otherwise great project and thank you for your hard work!

best.
Joe

**Comment by adavie1** [comment]
You'll need to use this CDN: https://cdnjs.cloudflare.com/ajax/libs/blaze/3.6.3/blaze.min.css.
Blaze CSS has gone away, and is replaced by Blaze UI. See comments on the github page.
