### ISSUE TITLE
issue on riotgear2 website 

### ISSUE THREAD

**Issue by infuzz** [riotgear2/riotgear2.github.io#3]
Hello, seems there is an issue on riotgear2 website 
Balzecss is not applied at all. Got this error in console :
Refused to apply style from 'https://unpkg.com/blaze@5.0.0/index.js' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by adavie1** [comment]
Thanks for the comment. Apologies for the very slowww reply. I'll look into it now.

**Comment by adavie1** [comment]
The Blaze CSS site no longer exits. They have pulled the CDN repos as well.
