### ISSUE TITLE
Where is Blaze CSS?

### ISSUE THREAD

**Issue by KempWatson** [riotgear2/riotgear2.github.io#4]
Site seems to have disappeared... is RiotGear still functional, or dead too?

**Comment by adavie1** [comment]
Yes, Blaze.css has been replaced by [Blaze UI](https://www.blazeui.com/)
As to RiotGear, it's very dormant! :-P
Because of the change in Blaze, it would require a total re-write of the framework, and I'm still pondering whether it's worth the effort, or to focus on other areas.
